package com.svcsolicitarcredito.domain.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.svcsolicitarcredito.domain.entity.enumerators.TipoEvento;
import lombok.Data;
import org.joda.time.DateTime;
import org.springframework.data.annotation.Id;

import javax.persistence.Entity;
import java.util.Date;
import java.util.UUID;

@Data
@Entity
@DynamoDBTable(tableName  = "Pedidos")
@JsonIgnoreProperties(ignoreUnknown=true)
public class EventoPedidoCredito {

  @Id
  private SolicitarCreditoID id;

  @DynamoDBHashKey(attributeName = "codigo_pedido_credito")
  public UUID getCodigoPedidoCredito() {
    return id != null ? id.getCodigoPedidoCredito() : null;
  }

  @DynamoDBRangeKey(attributeName = "chave_ordenacao")
  public String getQualifier() {
    return id != null ? id.getQualifier() : null;
  }

  public void setCodigoPedidoCredito(UUID codigoPedidoCredito) {
    if (id == null) {
      id = new SolicitarCreditoID();
    }
    id.setCodigoPedidoCredito(codigoPedidoCredito);
  }

  public void setQualifier(String qualifier) {
    if (id == null) {
      id = new SolicitarCreditoID();
    }
    id.setQualifier(qualifier);
  }

  @DynamoDBAttribute(attributeName = "codigo_evento")
  @DynamoDBAutoGeneratedKey
  private String codigoEvento;

  @DynamoDBAutoGeneratedTimestamp
  @DynamoDBAttribute(attributeName = "data_hora_evento")
  private Date dataHoraEvento;

  @DynamoDBAttribute(attributeName = "origem_evento")
  private String origemEvento;

  @DynamoDBAttribute(attributeName = "dados_evento_alteracao")
  private String dadosEventoAlteracao; //{'status_pedido':'em_processamento', 'valor_pedido':'1000'}

  private String detalhes; // evento de alteração de status e valor

  @DynamoDBAttribute(attributeName = "tipo_evento")
  @DynamoDBTypeConvertedEnum
  private TipoEvento tipoEvento;


  public String getCodigoEvento() {
    return codigoEvento;
  }

  public void setCodigoEvento(String codigoEvento) {
    this.codigoEvento = codigoEvento;
  }

  public Date getDataHoraEvento() {
    return dataHoraEvento;
  }

  public void setDataHoraEvento(Date dataHoraEvento) {
    this.dataHoraEvento = dataHoraEvento;
  }

  public String getOrigemEvento() {
    return origemEvento;
  }

  public void setOrigemEvento(String origemEvento) {
    this.origemEvento = origemEvento;
  }

  public String getDadosEventoAlteracao() {
    return dadosEventoAlteracao;
  }

  public void setDadosEventoAlteracao(String dadosEventoAlteracao) {
    this.dadosEventoAlteracao = dadosEventoAlteracao;
  }

  public String getDetalhes() {
    return detalhes;
  }

  public void setDetalhes(String detalhes) {
    this.detalhes = detalhes;
  }

  public TipoEvento getTipoEvento() {
    return tipoEvento;
  }

  public void setTipoEvento(TipoEvento tipoEvento) {
    this.tipoEvento = tipoEvento;
  }
}

